title: jekyll-rtd-theme
description: Just another documentation theme compatible with GitHub Pages

theme: null

baseurl:"" # the subpath of your site, e.g. /blog/
url:"https://polosesy/github.io/" # the base hostname & protocol for your site

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
